### ISSUE TITLE
confusion about HPOBench experiments

### ISSUE THREAD

**Issue by zien-fan** [jointentropysearch/JointEntropySearch#2]
1.How to set xmin and xmin for HPOBench experiments?
2.How to run experiments about HPOBench?

**Comment by zien-fan** [comment]
In GP prior experiments,  how to calculate max f(x), which is the first term of simple and inference regret? I think it may be calculate by fine grid and we can regard the max value obtained by fine grid as the max value of true function f(x). In addition, why inference regret is unobtainable?

**Comment by hvarfner** [comment]
Sorry for the terribly slow response, but no, it does not. However, I would strongly suggest using the [botorch variant of JES](https://github.com/pytorch/botorch/blob/main/botorch/acquisition/joint_entropy_search.py), which also has a corresponding notebook tutorial!
