### ISSUE TITLE
Hardware Requirements

### ISSUE THREAD

**Issue by IlterOnatKorkmaz** [jointentropysearch/JointEntropySearch#3]
Does this repository require a GPU? I am getting "Segmentation violation" errors and I suspect it is because my current workspace does not have a GPU.

**Comment by hvarfner** [comment]
Sorry for the terribly slow response, but no, it does not. However, I would strongly suggest using the [botorch variant of JES](https://github.com/pytorch/botorch/blob/main/botorch/acquisition/joint_entropy_search.py), which also has a corresponding notebook tutorial!
